tap "homebrew/science"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "aria2"
brew "gcc"
brew "arpack"
brew "autojump"
brew "boost"
brew "cmake"
brew "cookiecutter"
brew "duti"
brew "epstool"
brew "fftw"
brew "fig2dev"
brew "flac"
brew "fltk"
brew "fontconfig"
brew "fzf"
brew "gd"
brew "gdbm"
brew "gist"
brew "git"
brew "git-lfs"
brew "gl2ps"
brew "glpk"
brew "gnuplot"
brew "graphicsmagick"
brew "graphviz"
brew "hdf5"
brew "hub"
brew "icu4c"
brew "openssl"
brew "libogg"
brew "libsndfile"
brew "libyaml"
brew "mackup"
brew "mas"
brew "metis"
brew "ncdu"
brew "node"
brew "python"
brew "octave"
brew "opencv"
brew "openssl@1.1"
brew "pandoc"
brew "perl"
brew "pyqt"
brew "ruby"
brew "shark"
brew "speedtest-cli"
brew "telnet"
brew "terminal-notifier"
brew "thefuck"
brew "tmux"
brew "vim", args: ["with-lua"]
brew "wget"
brew "you-get"
cask "adobe-acrobat-reader"
cask "aerial"
cask "agenda"
cask "alfred"
cask "aliwangwang"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "bettertouchtool"
cask "bilibili"
cask "cacher"
cask "cajviewer"
cask "charles"
cask "coconutbattery"
cask "commander-one"
cask "dash"
cask "day-o"
cask "dictunifier"
cask "discord"
cask "docker"
cask "evernote"
cask "firefox"
cask "flash-player"
cask "fliqlo"
cask "gas-mask"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "ichm"
cask "iina"
cask "insomniax"
cask "istat-menus"
cask "iterm2"
cask "karabiner"
cask "keycastr"
cask "kitematic"
cask "licecap"
cask "liteicon"
cask "lyricsx"
cask "macpass"
cask "mactex-no-ghostscript"
cask "macvim"
cask "mounty"
cask "muzzle"
cask "neteasemusic"
cask "notion"
cask "papers"
cask "pdfexpert"
cask "pomotodo"
cask "qq"
cask "qqmusic"
cask "rocket"
cask "shadowsocksx-ng"
cask "sketch"
cask "skim"
cask "snipaste"
cask "sourcetree"
cask "spechtlite"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "teamspeak-client"
cask "telegram-desktop"
cask "termhere"
cask "the-unarchiver"
cask "transmission"
cask "vanilla"
cask "visual-studio-code"
cask "wiznote"
cask "zotero"
cask "homebrew/cask-fonts/font-camingocode"
cask "homebrew/cask-fonts/font-fira-mono-for-powerline"
cask "homebrew/cask-fonts/font-firacode-nerd-font"
cask "homebrew/cask-fonts/font-menlo-for-powerline"
cask "homebrew/cask-fonts/font-noto-mono-for-powerline"
cask "homebrew/cask-fonts/font-noto-sans-cjk-sc"
cask "homebrew/cask-fonts/font-noto-serif-cjk-sc"
cask "homebrew/cask-fonts/font-source-han-serif-el-m"
cask "homebrew/cask-versions/java8"
cask "homebrew/cask-versions/microsoft-remote-desktop-beta"
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "HazeOver", id: 430798174
mas "iMovie", id: 408981434
mas "iPic", id: 1101244278
mas "Irvue", id: 1039633667
mas "Jietu", id: 1059334054
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Maipo", id: 789066512
mas "miniQpicview", id: 1314842898
mas "MWeb", id: 954188948
mas "Noizio", id: 928871589
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Polarr Photo Editor Lite", id: 1077124956
mas "ScriptFlow", id: 994939623
mas "TickTick", id: 966085870
mas "Todoist", id: 585829637
mas "Wallpaper Wizard", id: 1266674560
mas "WeChat", id: 836500024
mas "订票助手", id: 1163682213
