tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask "java8"
brew "openssl"
brew "aria2"
brew "gcc"
brew "arpack"
brew "autojump"
brew "bat"
brew "icu4c"
brew "boost"
brew "fontconfig"
brew "gdbm"
brew "python"
brew "cmake"
brew "cookiecutter"
brew "duti"
brew "emacs"
brew "epstool"
brew "fcitx-remote-for-osx"
brew "libogg"
brew "flac"
brew "libsndfile"
brew "fftw"
brew "fig2dev"
brew "fltk"
brew "fontforge"
brew "fzf"
brew "gd"
brew "gist"
brew "git"
brew "git-lfs"
brew "gl2ps"
brew "glpk"
brew "gnuplot"
brew "go"
brew "graphicsmagick"
brew "graphviz"
brew "hdf5"
brew "hub"
brew "hugo"
brew "libyaml"
brew "mackup"
brew "mas"
brew "metis"
brew "ncdu"
brew "neovim", args: ["HEAD"]
brew "node"
brew "numpy", link: false
brew "octave"
brew "openssl@1.1"
brew "pandoc"
brew "perl"
brew "polipo"
brew "pyenv"
brew "pyqt"
brew "ranger"
brew "redis"
brew "ruby"
brew "speedtest-cli"
brew "telnet"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "vim"
brew "wget"
brew "yarn"
brew "you-get"
cask "adobe-acrobat-reader"
cask "aerial"
cask "agenda"
cask "alfred"
cask "aliwangwang"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "bettertouchtool"
cask "betterzip"
cask "cajviewer"
cask "cakebrew"
cask "caption"
cask "clashx"
cask "clion"
cask "coconutbattery"
cask "coderunner"
cask "commander-one"
cask "dash"
cask "day-o"
cask "dictunifier"
cask "discord"
cask "docker"
cask "dozer"
cask "dropbox"
cask "edex-ui"
cask "evernote"
cask "expressions"
cask "firefox"
cask "flash-player"
cask "fliqlo"
cask "font-camingocode"
cask "font-cooper-hewitt"
cask "font-fantasque-sans-mono"
cask "font-fantasquesansmono-nerd-font"
cask "font-fira-mono-for-powerline"
cask "font-firacode-nerd-font"
cask "font-fontawesome"
cask "font-ibm-plex"
cask "font-menlo-for-powerline"
cask "font-mononoki-nerd-font"
cask "font-museo"
cask "font-noto-mono-for-powerline"
cask "font-noto-sans-cjk-sc"
cask "font-noto-serif-cjk-sc"
cask "font-raleway"
cask "font-sarasa-gothic"
cask "font-source-han-serif-el-m"
cask "font-source-han-serif-sb-h"
cask "fork"
cask "gas-mask"
cask "gitup"
cask "google-backup-and-sync"
cask "google-chrome-beta"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "handbrake"
cask "ichm"
cask "iina"
cask "imageoptim"
cask "insomniax"
cask "istat-menus"
cask "iterm2"
cask "karabiner"
cask "keycastr"
cask "kitematic"
cask "lepton"
cask "licecap"
cask "liteicon"
cask "lyricsx"
cask "macpass"
cask "mactex-no-gui"
cask "macvim"
cask "mailspring"
cask "mathpix-snipping-tool"
cask "microsoft-remote-desktop-beta"
cask "mounty"
cask "musicbrainz-picard"
cask "muzzle"
cask "neteasemusic"
cask "notion"
cask "oni"
cask "pdf-expert"
cask "pomotodo"
cask "proxifier"
cask "qlcolorcode"
cask "qlstephen"
cask "qq"
cask "qqmusic"
cask "recents"
cask "rocket"
cask "shadowsocksx-ng"
cask "sip"
cask "sketch"
cask "skim"
cask "snipaste"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "surge"
cask "telegram-desktop"
cask "termhere"
cask "the-unarchiver"
cask "transmission"
cask "typora"
cask "vanilla"
cask "visual-studio-code"
cask "vox"
cask "xquartz"
cask "zotero"
mas "co.polarr.ppeosx.lite", id: 1077124956
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.crowdcafe.windowmagnet", id: 441258766
mas "com.dejal.timeout.free", id: 402592703
mas "com.fancymax.12306ForMac", id: 1163682213
mas "com.fasthatchapps.gifgrabberosx", id: 668208984
mas "com.helloresolven.GIF-Brewery-3", id: 1081413713
mas "com.jumsoft.money.macos", id: 1185488696
mas "com.kryolokovlin.Noizio", id: 928871589
mas "com.leonspok.osx.Irvue", id: 1039633667
mas "com.macpaw.WallWiz", id: 1266674560
mas "com.naman14.muzeimacos", id: 1203123639
mas "com.pointum.hazeover", id: 430798174
mas "com.reederapp.rkit2.mac", id: 880001334
mas "com.shapeservices.implusosx", id: 1137958278
mas "com.softmastx.ScriptFlow", id: 994939623
mas "com.tencent.JietuMac", id: 1059334054
mas "com.tencent.miniqpicview", id: 1314842898
mas "com.tencent.xinWeChat", id: 836500024
mas "com.TickTick.task.mac", id: 966085870
mas "com.todoist.mac.Todoist", id: 585829637
mas "com.wutian.weibo", id: 789066512
mas "com.zzd.Xnip", id: 1221250572
mas "net.shinyfrog.bear", id: 1091189122
mas "net.toolinbox.ipic", id: 1101244278
