" 简介 {
" 设置本文档的默认折叠模式为标记
" 参考：http://vim.wikia.com/wiki/Modeline_magic
" vim: foldmethod=marker foldlevel=0 foldmarker={,}
" 自己使用的 Vim 配置
" 主要平台：macOS,Windows,Linux / 终端：iTerm2,Windows Terminal /
" 主题：Solarized / 推荐字体：Nerd Fonts, SarasaGothic
" Copyright 2019 @yzlnew
" }

" 环境设置 {
    " 识别平台 {
        silent function! OSX()
            return has('macunix')
        endfunction
        silent function! LINUX()
            return has('unix') && !has('macunix') && !has('win32unix')
        endfunction
        silent function! WINDOWS()
            return  (has('win32') || has('win64'))
        endfunction
    " }
    " Shell {
        set nocompatible        " Must be first line
        if !WINDOWS()
            set shell=/bin/zsh
        endif
        " if WINDOWS()
            " set shell=powershell.exe
        " endif
    " }
    " runtimepath {
      set runtimepath+=$HOME/.vim
    " }
    " NeoVim {
        if has('nvim')
            set pyx=3
            set wildoptions=pum
        endif
    " }
" }

" 插件管理 {
" 使用 vim-plug 进行插件管理

    if !WINDOWS()
        if empty(glob('~/.vim/autoload/plug.vim'))
          silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
            \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
          autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
        endif
    endif

    call plug#begin('~/.vim/plugged')
        if WINDOWS()
            if has('nvim')
                Plug 'yzlnew/smartim'
            endif
        else
            Plug 'dangxuandev/fcitx-vim-osx'    " 正常模式使用英文输入法
        endif
        Plug 'scrooloose/nerdtree'              " 目录树
        if has('nvim')
          Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
        else
          Plug 'Shougo/defx.nvim'
          Plug 'roxma/nvim-yarp'
          Plug 'roxma/vim-hug-neovim-rpc'
        endif
        Plug 'alpertuna/vim-header'             " 头部信息生成
        Plug 'kristijanhusak/defx-icons'
        Plug 'kristijanhusak/defx-git'
        Plug 'vimwiki/vimwiki'
        Plug 'tpope/vim-unimpaired'             " 一些有用的快捷键
        Plug 'liuchengxu/vista.vim'             " tags, symbols
        Plug 'junegunn/vim-easy-align'          " 文本对齐
        " Plug 'francoiscabrol/ranger.vim'        " Ranger
        Plug 'ryanoasis/vim-devicons'           " 文件图标
        Plug 'mhinz/vim-startify'               " 启动页
        Plug 'cespare/vim-toml'                 " 支持 TOML
        Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
        Plug 'junegunn/fzf.vim'                 " fzf 文件模糊搜索
        Plug 'wakatime/vim-wakatime'            " Wakatime 编程记录
        Plug 'w0rp/ale'                         " 代码分析和自动修正
        Plug 'junegunn/vim-emoji'               " Emoji
        Plug 'mhinz/vim-signify'                " Git 标记
        Plug 'arcticicestudio/nord-vim'         " 暗色主题
        Plug 'iCyMind/NeoSolarized'             " 支持 True Color 的主题
        Plug 'lifepillar/vim-solarized8'        " 支持 nvim 的主题
        Plug 'altercation/vim-colors-solarized' " Solarized 主题
        " Plug 'rafi/awesome-vim-colorschemes'
        Plug 'godlygeek/tabular'                " 对齐文本
        Plug 'plasticboy/vim-markdown'          " 支持 Markdown
        Plug 'suan/vim-instant-markdown'        " Markdown 预览
        Plug 'skywind3000/asyncrun.vim'         " 异步执行命令行指令
        Plug 'itchyny/lightline.vim'            " Lightline
        Plug 'mengelbrecht/lightline-bufferline'
        Plug 'maximbaz/lightline-ale'
        Plug 'SirVer/ultisnips'                 " 代码片段引擎
        Plug 'honza/vim-snippets'               " 代码片段
        Plug 'tpope/vim-fugitive'               " Git
        Plug 'tpope/vim-surround'               " 更改包裹
        Plug 'tpope/vim-commentary'             " 快速注释 `gcc`
        Plug 'jiangmiao/auto-pairs'             " 括号自动配对
        Plug 'luochen1990/rainbow'              " 彩虹括号
        Plug 'easymotion/vim-easymotion'        " 快速跳转
        Plug 'wellle/targets.vim'               " 额外的文本对象
        Plug 'lilydjwg/colorizer'               " RGB 颜色显示
        Plug 'mzlogin/vim-markdown-toc'         " Markdown 目录生成
        Plug 'lervag/vimtex'                    " LaTeX
        Plug 'liuchengxu/vim-which-key'
        Plug 'vim-scripts/ReplaceWithRegister'  " 粘贴并替换 `gr`
        Plug 'patstockwell/vim-monokai-tasty'   " 以下都是一些主题
        Plug 'joshdick/onedark.vim'
        Plug 'rakr/vim-one'
        Plug 'kaicataldo/material.vim'
        Plug 'dikiaap/minimalist'
        Plug 'hzchirs/vim-material'
        " Plug 'endel/vim-github-colorscheme'
        Plug 'cormacrelf/vim-colors-github'
        Plug 'sainnhe/vim-color-forest-night'
        Plug 'Rigellute/shades-of-purple.vim'
        Plug 'heavenshell/vim-pydocstring'      " 生成 Python docstring
        if WINDOWS()
            Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.cmd'}
        else
            Plug 'neoclide/coc.nvim', {'tag': '*', 'do': './install.sh'}
        endif
    call plug#end()
" }

" 基础设置 {
    set encoding=utf-8          " YCM 要求
    if WINDOWS()                " gVim 菜单乱码
        source $VIMRUNTIME/delmenu.vim
        source $VIMRUNTIME/menu.vim
    endif
    set ttyfast
    set lazyredraw
    set history=500             " 历史指令数量
    filetype plugin indent on   " 文件类型
    syntax enable               " 支持语法高亮
    set mouse=a                 " 使用鼠标
    set mousehide               " 输入时隐藏鼠标指针
    scriptencoding utf-8        " UTF-8 文件编码
    set clipboard=unnamed       " 系统剪贴板使用匿名寄存器
    set shortmess+=filmnrxoOtT  " 减少和缩写消息提示
    set viewoptions=folds,options,cursor,unix,slash
    set virtualedit=onemore     " 允许光标移动到超过行尾的位置
    set nospell                 " 禁用拼写检查
    set hidden                  " 隐藏缓冲区
    set tags=./.tags;,.tags
    " 自动切换到当前缓冲区文件目录
    autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h |
    " 编辑 git commit 时光标指向第一行
    au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])
    " 光标回到之前位置
    function! ResCur()
        if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit'
            silent normal! g`"
            return 1
        endif
    endfunction
    augroup resCur
        autocmd!
        autocmd BufWinEnter * call ResCur()
    augroup END
    " 备份 {
        set nobackup
        set nowritebackup
        if !isdirectory($HOME . '/.vim/files')
            call mkdir($HOME . '/.vim/files')
            " call mkdir($HOME . '/.vim/files/backup')
            call mkdir($HOME . '/.vim/files/swap')
            call mkdir($HOME . '/.vim/files/undo')
        endif
        " set backupdir=$HOME/.vim/files/backup/
        " set backupext=-vimbackup
        " set backupskip=
        set directory=$HOME/.vim/files/swap//
        if has('persistent_undo')
            set undofile
            set undodir=$HOME/.vim/files/undo/
            set undolevels=1000
            set undoreload=10000
        endif
    " }
" }

" UI 设定 {
    " 主题 {
    " 由于 macOS 的终端不支持 True Color，建议使用 iTerm2
    " 另支持正常和插入模式不同的光标样式
        set termguicolors

        let g:vim_monokai_tasty_italic = 1
        let g:solarized_term_italics=1
        let g:neosolarized_italic=1
        let g:onedark_terminal_italics=1
        let g:material_terminal_italics = 1
        let g:material_theme_style = 'default'
        let g:nord_italic = 1
        let g:nord_cursor_line_number_background = 1

        if OSX()
            let iterm_profile = $ITERM_PROFILE
            if iterm_profile == "robin_dark"
                set background=dark
            else
                set background=light
            endif
            colorscheme solarized8

            if $TERM_PROGRAM == 'Apple_Terminal'
                let g:solarized_use16 = 0
                let &t_SI.="\e[5 q"
                let &t_SR.="\e[4 q"
                let &t_EI.="\e[1 q"
            endif
            if $TERM_PROGRAM == 'iTerm.app'
                set termguicolors
                let &t_SI = "\<Esc>]50;CursorShape=1\x7"
                let &t_SR = "\<Esc>]50;CursorShape=2\x7"
                let &t_EI = "\<Esc>]50;CursorShape=0\x7"
            endif
        endif

        if LINUX()
            set background=light
            colorscheme github
        endif

        if WINDOWS()
            set background=light
            colorscheme github
        endif

        if has('gui_running')
            if WINDOWS()
                set guifont=Sarasa\ Mono\ SC:h14
                set guifontwide=Sarasa\ Mono\ SC:h14
            else
                set guifont=OperatorMonoSSm\ NF:h14
            endif
            set guioptions -=T
            " highlight clear LineNr
            " highlight clear SignColumn
            " highlight LineNr guibg=NONE
            " highlight Comment gui=italic
        endif
        " highlight Keyword cterm=italic gui=italic
    " }
    set noshowmode
    set colorcolumn=81
    if has('cmdline_info')
        set ruler
        set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
        set showcmd
    endif

    if has('statusline')
        set laststatus=2
        set statusline=%<%f\
        set statusline+=%w%h%m%r
        set statusline+=\ [%{&ff}/%Y]
        set statusline+=\ [%{getcwd()}]
        set statusline+=%=%-14.(%l,%c%V%)\ %p%%
    endif
    set showtabline=2
    set number                  " 显示行号
    set relativenumber
    set cursorline              " 高亮当前行
    " highlight clear SignColumn  " 去除标志列背景
    " highlight clear LineNr      " 去除行号背景
    " hi Normal     ctermbg=NONE guibg=NONE
    hi LineNr     ctermbg=NONE guibg=NONE
    hi SignColumn ctermbg=NONE guibg=NONE
    set backspace=indent,eol,start
    set showmatch               " 括号匹配
    set incsearch               " 同步搜索
    set hlsearch                " 高亮搜索
    set winminheight=0          " 允许窗口高度为0
    set ignorecase              " 大小写不敏感
    set smartcase               " 使用大写字符时开启大小写敏感
    set wildmenu                " Tab 补全候选
    " set wildmode=list:longest,full
    set whichwrap=b,s,<,>,[,]   " 在行首行尾可以移动到另一行
    set scrolljump=5            " 光标离开屏幕时滚动的行数
    set scrolloff=3             " 收尾留的行数
    set nofoldenable            " 关闭代码折叠
    set list                    " 显示可能引起的空白字符
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:.
    set fillchars+=vert:│
" }

" 格式化 {
    set fo+=mB
    set sidescroll=1
    set conceallevel=2                   " Markdown 用到此项做语法隐藏
    set nowrap
    set autoindent
    set smartindent
    set shiftwidth=4
    set expandtab
    set tabstop=4
    set softtabstop=4
    set nojoinspaces
    set splitright
    set splitbelow
    set pastetoggle=<F12>                " 进入粘贴模式
    autocmd BufWritePre * %s/\s\+$//e    " 保存时清除行末空格
" }

" 快捷键 {
    let mapleader=','
    " 窗口快速移动 {
        map <C-J> <C-W>j<C-W>_
        map <C-K> <C-W>k<C-W>_
        map <C-L> <C-W>l<C-W>_
        map <C-H> <C-W>h<C-W>_
    " }
    " 折行移动到显示的下一行
    noremap j gj
    noremap k gk
    nnoremap Y y$       " 从光标处复制到行尾
    " 折叠选项 {
        nmap <leader>f0 :set foldlevel=0<CR>
        nmap <leader>f1 :set foldlevel=1<CR>
        nmap <leader>f2 :set foldlevel=2<CR>
        nmap <leader>f3 :set foldlevel=3<CR>
        nmap <leader>f4 :set foldlevel=4<CR>
        nmap <leader>f5 :set foldlevel=5<CR>
        nmap <leader>f6 :set foldlevel=6<CR>
        nmap <leader>f7 :set foldlevel=7<CR>
        nmap <leader>f8 :set foldlevel=8<CR>
        nmap <leader>f9 :set foldlevel=9<CR>
    " }
    nmap <silent> <leader>/ :nohlsearch<CR>    " 清除搜索结果高亮

    " 进入当前文件的目录
    cmap cwd lcd %:p:h
    cmap cd. lcd %:p:h

    " 可视模式缩进不退出可视模式
    vnoremap < <gv
    vnoremap > >gv
    " 可视模式选择内容可以使用重复操作
    vnoremap . :normal .<CR>

    " 水平移动
    map zl zL
    map zh zH

    " Terminal
    tnoremap <Esc> <C-\><C-n>
" }

" 插件设定 {
    " Signify {
        let g:signify_vsc_list = ['git']
        let g:signify_realtime = 1
        let g:signify_line_highlight = 1
    " }
    " Lightline {
        let g:lightline = {}
        let g:lightline.colorscheme = 'github'
        let g:lightline.component = {
              \  'me': '@yzlnew',
              \  'lineinfo': '⭡ %3l:%-2v',
              \  }
        let g:lightline.component_function = {
              \  'cocstatus': 'coc#status',
              \  'readonly': 'LightlineReadonly',
              \  'fugitive': 'LightlineFugitive',
              \  'filetype': 'Filetype',
              \  'fileformat': 'Fileformat',
              \  'modified': 'LightlineModified'
              \  }
        let g:lightline.component_expand = {
              \  'linter_checking': 'lightline#ale#checking',
              \  'linter_warnings': 'lightline#ale#warnings',
              \  'linter_errors': 'lightline#ale#errors',
              \  'linter_ok': 'lightline#ale#ok',
              \  'buffers': 'lightline#bufferline#buffers'
              \  }
        let g:lightline.component_type = {
              \  'linter_checking': 'left',
              \  'linter_warnings': 'warning',
              \  'linter_errors': 'error',
              \  'linter_ok': 'left',
              \  'buffers': 'tabsel'
              \  }
        let g:lightline#ale#indicator_checking = ""
        let g:lightline#ale#indicator_warnings = "!"
        let g:lightline#ale#indicator_errors = "×"
        let g:lightline#ale#indicator_ok = ""
        let g:lightline.tabline = {'left': [['buffers']], 'right': [['close']]}
        let g:lightline.active = {
              \  'left': [ [ 'mode', 'paste' ],
              \            [ 'fugitive', 'readonly', 'filename', 'modified', 'me' ] ],
              \  'right': [ [ 'cocstatus' ],
              \             [ 'lineinfo', 'percent' ],
              \             [ 'fileformat', 'fileencoding', 'filetype', 'charvaluehex' ] ]
              \  }
        let g:lightline#bufferline#enable_devicons = 1
        function! Filetype()
          return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
        endfunction
        function! Fileformat()
          return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
        endfunction
        function! LightlineReadonly()
            return &readonly ? '' : ''
        endfunction
        function! LightlineModified()
            return &ft =~ 'help\|vimfiler' ? '' : &modified ? '+' : &modifiable ? '' : '-'
        endfunction
        function! LightlineFugitive()
            if exists('*fugitive#head')
                let branch = fugitive#head()
                return branch !=# '' ? ' '.branch : ''
            endif
            return ''
        endfunction
    " }
    " ALE {
        let g:ale_enabled = 0
        let g:ale_set_highlights = 0
        let g:ale_sign_error = 'x'
        let g:ale_sign_warning = '!'
        let g:ale_echo_msg_format = "%severity%: %s  [%linter%]"
        let g:ale_echo_msg_error_str = "Error"
        let g:ale_echo_msg_info_str = "Info"
        let g:ale_echo_msg_warning_str = "Warning"
        let g:ale_writegood_use_global = 1
        let g:ale_change_sign_column_color = 0
        let g:ale_sign_column_always = 1
        let g:ale_fixers = {
        \   'python': ['black','isort','yapf'],
        \   'markdown': ['prettier','trim_whitespace'],
        \    'cpp': ['clang-format','trim_whitespace'],
        \}
    " }
    " Markdown {
        let g:tex_conceal = ""
        let g:vim_markdown_math = 1
        let g:vim_markdown_frontmatter = 1
        let g:vim_markdown_folding_disabled = 1
        " let g:mkdp_path_to_chrome = "open -a Google\\ Chrome"
        let g:instant_markdown_autostart = 0
    " }
    " fzf {
        let g:fzf_colors =
        \ { 'fg':      ['fg', 'Normal'],
          \ 'bg':      ['bg', 'Normal'],
          \ 'hl':      ['fg', 'Comment'],
          \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
          \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
          \ 'hl+':     ['fg', 'Statement'],
          \ 'info':    ['fg', 'PreProc'],
          \ 'border':  ['fg', 'Ignore'],
          \ 'prompt':  ['fg', 'Conditional'],
          \ 'pointer': ['fg', 'Exception'],
          \ 'marker':  ['fg', 'Keyword'],
          \ 'spinner': ['fg', 'Label'],
          \ 'header':  ['fg', 'Comment'] }
    " }
    " COC {
        " hi IncSearch gui=reverse
        nmap ge :CocCommand explorer<CR>
        inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
        inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
        inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
        autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
        set signcolumn=yes
        set updatetime=300
        " Use `[c` and `]c` to navigate diagnostics
        nmap <silent> [c <Plug>(coc-diagnostic-prev)
        nmap <silent> ]c <Plug>(coc-diagnostic-next)

        " Remap keys for gotos
        nmap <silent> gd <Plug>(coc-definition)
        nmap <silent> gy <Plug>(coc-type-definition)
        nmap <silent> gi <Plug>(coc-implementation)
        nmap <silent> gf <Plug>(coc-references)

        " Use K to show documentation in preview window
        nnoremap <silent> K :call <SID>show_documentation()<CR>

        function! s:show_documentation()
          if (index(['vim','help'], &filetype) >= 0)
            execute 'h '.expand('<cword>')
          else
            call CocAction('doHover')
          endif
        endfunction

        " Highlight symbol under cursor on CursorHold
        autocmd CursorHold * silent call CocActionAsync('highlight')

        " Remap for rename current word
        nmap <leader>rn <Plug>(coc-rename)

        " Remap for format selected region
        vmap <leader>f  <Plug>(coc-format-selected)
        nmap <leader>f  <Plug>(coc-format-selected)

        augroup mygroup
          autocmd!
          " Setup formatexpr specified filetype(s).
          autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
          " Update signature help on jump placeholder
          autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
        augroup end

        " Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
        vmap <leader>a  <Plug>(coc-codeaction-selected)
        nmap <leader>a  <Plug>(coc-codeaction-selected)

        " Remap for do codeAction of current line
        nmap <leader>ac  <Plug>(coc-codeaction)
        " Fix autofix problem of current line
        nmap <leader>qf  <Plug>(coc-fix-current)

        " Use `:Format` to format current buffer
        command! -nargs=0 Format :call CocAction('format')

        " Use `:Fold` to fold current buffer
        command! -nargs=? Fold :call     CocAction('fold', <f-args>)

    " }
    " UltiSnips {
        let g:UltiSnipsExpandTrigger = '<C-j>'
        let g:UltiSnipsJumpForwardTrigger = '<C-j>'
        let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
        let g:UltiSnipsEditSplit="vertical"
        let g:UltiSnipsSnippetsDir='~/.vim/my-snippets'
        let g:UltiSnipsSnippetDirectories=["UltiSnips", "my-snippets"]
    " }
    " EasyMotion {
        map <Leader>L <Plug>(easymotion-bd-jk)
    " }
    " NERDTree {
        map <leader>nt :NERDTreeToggle<CR>
        nmap <leader>ntf :NERDTreeFind<CR>

        let NERDTreeShowBookmarks=1
        let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$']
        let NERDTreeChDirMode=0
        let NERDTreeQuitOnOpen=1
        let NERDTreeMouseMode=2
        let NERDTreeShowHidden=1
        let NERDTreeKeepTreeInNewTab=1
        let g:NERDTreeHijackNetrw=1
    " }
    " defx {
        nmap <leader>df :Defx<CR>
        call defx#custom#option('_', {
              \ 'columns': 'mark:git:indent:icons:filename',
              \ 'winwidth': 40,
              \ 'split': 'vertical',
              \ 'direction': 'topleft',
              \ 'show_ignored_files': 0,
              \ 'buffer_name': '',
              \ 'toggle': 1,
              \ 'resume': 1
              \ })
        call defx#custom#column('icon', {
              \ 'directory_icon': '',
              \ 'opened_icon': '',
              \ 'root_icon': ""
              \ })
        call defx#custom#column('mark', {
              \ 'readonly_icon': "",
              \ 'selected_icon': "",
              \ })
        let g:defx_git#indicators = {
          \ 'Modified'  : '∙',
          \ 'Staged'    : '+',
          \ 'Untracked' : '*',
          \ 'Renamed'   : '→',
          \ 'Unmerged'  : '=',
          \ 'Ignored'   : '☒',
          \ 'Deleted'   : '✗',
          \ 'Unknown'   : '?'
          \ }
        autocmd FileType defx call s:defx_my_settings()
        function! s:defx_my_settings() abort
          setlocal nonumber
          setlocal listchars=
          setlocal foldcolumn=0
          " setlocal buftype=nofile
          setlocal noswapfile
          setlocal nolist
          setlocal nospell
          setlocal cursorline

          " Define mappings
          nnoremap <silent><buffer><expr>   <CR>            defx#is_directory() ? defx#do_action('open_or_close_tree') : defx#do_action('multi', ['drop'])
          nnoremap <silent><buffer><expr>   <2-LeftMouse>   defx#is_directory() ? defx#do_action('open_or_close_tree') : defx#do_action('multi', ['drop'])
          nnoremap <silent><buffer><expr>   c               defx#do_action('copy')
          nnoremap <silent><buffer><expr>   m               defx#do_action('move')
          nnoremap <silent><buffer><expr>   p               defx#do_action('paste')
          " nnoremap <silent><buffer><expr>   l               defx#do_action('open')
          nnoremap <silent><buffer><expr>   E               defx#do_action('open', 'vsplit')
          nnoremap <silent><buffer><expr>   P               defx#do_action('open', 'pedit')
          nnoremap <silent><buffer><expr>   t               defx#do_action('open', 'tabnew')
          nnoremap <silent><buffer><expr>   o               defx#do_action('open_or_close_tree')
          nnoremap <silent><buffer><expr>   K               defx#do_action('new_directory')
          nnoremap <silent><buffer><expr>   N               defx#do_action('new_file')
          nnoremap <silent><buffer><expr>   M               defx#do_action('new_multiple_files')
          nnoremap <silent><buffer><expr>   C               defx#do_action('toggle_columns', 'mark:git:icons:filename:size:time')
          nnoremap <silent><buffer><expr>   S               defx#do_action('toggle_sort', 'time')
          nnoremap <silent><buffer><expr>   d               defx#do_action('remove')
          nnoremap <silent><buffer><expr>   r               defx#do_action('rename')
          nnoremap <silent><buffer><expr>   !               defx#do_action('execute_command')
          nnoremap <silent><buffer><expr>   x               defx#do_action('execute_system')
          nnoremap <silent><buffer><expr>   yy              defx#do_action('yank_path')
          nnoremap <silent><buffer><expr>   .               defx#do_action('toggle_ignored_files')
          " nnoremap <silent><buffer><expr>   ;               defx#do_action('repeat')
          nnoremap <silent><buffer><expr>   <C-o>           defx#do_action('cd', ['..'])
          nnoremap <silent><buffer><expr>   <C-i>           defx#do_action('open')
          nnoremap <silent><buffer><expr>   q               defx#do_action('quit')
          nnoremap <silent><buffer><expr>   <Space>         defx#do_action('toggle_select') . 'j'
          nnoremap <silent><buffer><expr>   *               defx#do_action('toggle_select_all')
          " nnoremap <silent><buffer><expr>   j               line('.') == line('$') ? 'gg' : 'j'
          " nnoremap <silent><buffer><expr>   k               line('.') == 1 ? 'G' : 'k'
          nnoremap <silent><buffer><expr>   <C-l>           defx#do_action('redraw')
          nnoremap <silent><buffer><expr>   <C-g>           defx#do_action('print')
          nnoremap <silent><buffer><expr>   cd              defx#do_action('change_vim_cwd')
        endfunction
    " }
    " NERDCommenter {
    let g:NERDSpaceDelims=1
    " }
    " startify {
        let g:ascii = [
        \ '    |\__/,| ',
        \ '  _.|o o  |_ Hello, Robin!',
        \ ]
        let g:startify_custom_header = g:ascii + startify#fortune#boxed()
    " }
    " AutoPairs {
        let g:AutoPairsShortcutFastWrap = '<leader>fw'
        let g:AutoPairsShortcutJump = '<leader>j'
    " }
    " Vimtex {
        if OSX()
            let g:vimtex_view_enabled = 1
            let g:vimtex_view_method = 'skim'
        endif
        if has('nvim')
            let g:vimtex_compiler_progname = 'nvr'
        endif
        if WINDOWS()
            let g:vimtex_view_general_viewer = 'SumatraPDF'
            let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
            let g:vimtex_view_general_options_latexmk = '-reuse-instance'
        endif
    " }
    " gutentags {
        " gutentags 搜索工程目录的标志，碰到这些文件/目录名就停止向上一级目录递归
        let g:gutentags_project_root = ['.root', '.svn', '.git', '.hg', '.project']

        " 所生成的数据文件的名称
        let g:gutentags_ctags_tagfile = '.tags'

        " 将自动生成的 tags 文件全部放入 ~/.cache/tags 目录中，避免污染工程目录
        let s:vim_tags = expand('~/.cache/tags')
        let g:gutentags_cache_dir = s:vim_tags

        " 配置 ctags 的参数
        let g:gutentags_ctags_extra_args = ['--fields=+niazS', '--extra=+q']
        let g:gutentags_ctags_extra_args += ['--c++-kinds=+px']
        let g:gutentags_ctags_extra_args += ['--c-kinds=+px']
    " }
    " Smartim {
        let g:smartim_default = '1033'
    " }
    " { header
        let g:header_field_author = '@yzlnew'
        let g:header_field_author_email = 'yzlnew@gmail.com'
        let g:header_auto_add_header = 0
    " }
    " highlightedyank {
        " highlight HighlightedyankRegion cterm=reverse gui=reverse
    " }
" }
