" 简介 {
" 设置本文档的默认折叠模式为标记
" 参考：http://vim.wikia.com/wiki/Modeline_magic
" vim: foldmethod=marker foldlevel=0 foldmarker={,}
" 自己使用的 Vim 配置
" 主要平台：macOS, Windows, Linux / 终端：iTerm2, Windows Terminal /
" 主题：Darcula / 推荐字体：Nerd Fonts, SarasaGothic
" Copyright 2020 @yzlnew
" }

" 环境设置 {
    " 识别平台 {
        silent function! OSX()
            return has('macunix')
        endfunction
        silent function! LINUX()
            return has('unix') && !has('macunix') && !has('win32unix')
        endfunction
        silent function! WINDOWS()
            return  (has('win32') || has('win64'))
        endfunction
    " }
    " Shell {
        set nocompatible        " Must be first line
        if !WINDOWS()
            set shell=/bin/zsh
        endif
        if WINDOWS() && !has('nvim')
            let winpypath = "C:\\Users\\11103475\\scoop\\apps\\python\\current"
            let &pythonthreedll= join([winpypath,"\\python38.dll"],"")
            let &pythonthreehome= winpypath
        endif
        if WINDOWS() && has('nvim')
            let g:python3_host_prog = join([winpypath,"\\python.exe"],"")
        endif
        if OSX()
            let g:python3_host_prog = '/usr/local/bin/python3'
            let g:loaded_python_provider = 0
            if has('gui_running')
                let &pythonthreedll="/usr/local/Frameworks/Python.framework/Versions/3.9/Python"
                let &pythonthreehome="/usr/local/Frameworks/Python.framework/Versions/3.9"
            endif
        endif
    " }
    " runtimepath {
      set runtimepath+=$HOME/.vim
    " }
    " NeoVim {
        if has('nvim')
            set pyx=3
            set wildoptions=pum
        endif
    " }
" }

source ~/dotfiles/Vim/plugins.vim
source ~/dotfiles/Vim/basic.vim
source ~/dotfiles/Vim/ui.vim
source ~/dotfiles/Vim/mappings.vim
source ~/dotfiles/Vim/plugin_settings.vim
